export LANG=ja_JP.UTF-8
alias ls='ls --color=auto'
alias ll='ls -l --color=auto'
alias la='ls -A --color=auto'
alias lla='ls -lA --color=auto'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias vim='nvim'
alias gvim='nvim-qt'
alias gcl='git clone'
alias gs='git status'
alias gl='git lol -n 5'
alias gll='git lol -n 15'
alias gml='git mylog -n 5'
alias gmll='git mylog -n 15'
alias ga='git add'
alias gcm='git commit -m'
alias gb='git branch'
alias gba='git branch -a'
alias gbc='git branch -c'
alias gck='git checkout'
alias grs='git rs'
alias gls='git ls-files'
alias glsr='git ls-remote'
alias gu='git ups'
alias gf='git fetch'
alias gm='git merge'
